// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_UploadResult
	//	*AgentMessage_DirectoryListing
	//	*AgentMessage_RuleStatus
	//	*AgentMessage_ErrorReport
	//	*AgentMessage_DryRunResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetUploadResult() *UploadResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_UploadResult); ok {
			return x.UploadResult
		}
	}
	return nil
}

func (x *AgentMessage) GetDirectoryListing() *DirectoryListing {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DirectoryListing); ok {
			return x.DirectoryListing
		}
	}
	return nil
}

func (x *AgentMessage) GetRuleStatus() *RuleStatusReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RuleStatus); ok {
			return x.RuleStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetErrorReport() *ErrorReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ErrorReport); ok {
			return x.ErrorReport
		}
	}
	return nil
}

func (x *AgentMessage) GetDryRunResult() *DryRunResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DryRunResult); ok {
			return x.DryRunResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_UploadResult struct {
	UploadResult *UploadResult `protobuf:"bytes,11,opt,name=upload_result,json=uploadResult,proto3,oneof"`
}

type AgentMessage_DirectoryListing struct {
	DirectoryListing *DirectoryListing `protobuf:"bytes,12,opt,name=directory_listing,json=directoryListing,proto3,oneof"`
}

type AgentMessage_RuleStatus struct {
	RuleStatus *RuleStatusReport `protobuf:"bytes,13,opt,name=rule_status,json=ruleStatus,proto3,oneof"`
}

type AgentMessage_ErrorReport struct {
	ErrorReport *ErrorReport `protobuf:"bytes,14,opt,name=error_report,json=errorReport,proto3,oneof"`
}

type AgentMessage_DryRunResult struct {
	DryRunResult *DryRunResult `protobuf:"bytes,15,opt,name=dry_run_result,json=dryRunResult,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_UploadResult) isAgentMessage_Payload() {}

func (*AgentMessage_DirectoryListing) isAgentMessage_Payload() {}

func (*AgentMessage_RuleStatus) isAgentMessage_Payload() {}

func (*AgentMessage_ErrorReport) isAgentMessage_Payload() {}

func (*AgentMessage_DryRunResult) isAgentMessage_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	QueueDepth    int32                  `protobuf:"varint,3,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	UploadBps     float32                `protobuf:"fixed32,4,opt,name=upload_bps,json=uploadBps,proto3" json:"upload_bps,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Disks         []*DiskInfo            `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *Heartbeat) GetUploadBps() float32 {
	if x != nil {
		return x.UploadBps
	}
	return 0
}

func (x *Heartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Heartbeat) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	FsType        string                 `protobuf:"bytes,4,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_proto_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DiskInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskInfo) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskInfo) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *DiskInfo) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

type UploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	StoragePath   string                 `protobuf:"bytes,3,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Etag          string                 `protobuf:"bytes,7,opt,name=etag,proto3" json:"etag,omitempty"`
	Success       bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FileMtime     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=file_mtime,json=fileMtime,proto3" json:"file_mtime,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	RetryCount    int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_proto_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResult.ProtoReflect.Descriptor instead.
func (*UploadResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResult) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *UploadResult) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadResult) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *UploadResult) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadResult) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UploadResult) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadResult) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *UploadResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UploadResult) GetFileMtime() *timestamppb.Timestamp {
	if x != nil {
		return x.FileMtime
	}
	return nil
}

func (x *UploadResult) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *UploadResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type DirectoryListing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Entries       []*FsEntry             `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryListing) Reset() {
	*x = DirectoryListing{}
	mi := &file_proto_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryListing) ProtoMessage() {}

func (x *DirectoryListing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryListing.ProtoReflect.Descriptor instead.
func (*DirectoryListing) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *DirectoryListing) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DirectoryListing) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectoryListing) GetEntries() []*FsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *DirectoryListing) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	Permissions   string                 `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsEntry) Reset() {
	*x = FsEntry{}
	mi := &file_proto_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEntry) ProtoMessage() {}

func (x *FsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEntry.ProtoReflect.Descriptor instead.
func (*FsEntry) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FsEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FsEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FsEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FsEntry) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *FsEntry) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

type RuleStatusReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuleId         string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	FilesProcessed int64                  `protobuf:"varint,4,opt,name=files_processed,json=filesProcessed,proto3" json:"files_processed,omitempty"`
	BytesUploaded  int64                  `protobuf:"varint,5,opt,name=bytes_uploaded,json=bytesUploaded,proto3" json:"bytes_uploaded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuleStatusReport) Reset() {
	*x = RuleStatusReport{}
	mi := &file_proto_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleStatusReport) ProtoMessage() {}

func (x *RuleStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleStatusReport.ProtoReflect.Descriptor instead.
func (*RuleStatusReport) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RuleStatusReport) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleStatusReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuleStatusReport) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *RuleStatusReport) GetFilesProcessed() int64 {
	if x != nil {
		return x.FilesProcessed
	}
	return 0
}

func (x *RuleStatusReport) GetBytesUploaded() int64 {
	if x != nil {
		return x.BytesUploaded
	}
	return 0
}

type ErrorReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReport) Reset() {
	*x = ErrorReport{}
	mi := &file_proto_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReport) ProtoMessage() {}

func (x *ErrorReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReport.ProtoReflect.Descriptor instead.
func (*ErrorReport) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorReport) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type DryRunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Files         []*DryRunFileResult    `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DryRunResult) Reset() {
	*x = DryRunResult{}
	mi := &file_proto_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunResult) ProtoMessage() {}

func (x *DryRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunResult.ProtoReflect.Descriptor instead.
func (*DryRunResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DryRunResult) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DryRunResult) GetFiles() []*DryRunFileResult {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DryRunResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DryRunFileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPath     string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	UploadPath    string                 `protobuf:"bytes,2,opt,name=upload_path,json=uploadPath,proto3" json:"upload_path,omitempty"`
	ParsedFields  map[string]string      `protobuf:"bytes,3,rep,name=parsed_fields,json=parsedFields,proto3" json:"parsed_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ComposeError  string                 `protobuf:"bytes,4,opt,name=compose_error,json=composeError,proto3" json:"compose_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DryRunFileResult) Reset() {
	*x = DryRunFileResult{}
	mi := &file_proto_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryRunFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunFileResult) ProtoMessage() {}

func (x *DryRunFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunFileResult.ProtoReflect.Descriptor instead.
func (*DryRunFileResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DryRunFileResult) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *DryRunFileResult) GetUploadPath() string {
	if x != nil {
		return x.UploadPath
	}
	return ""
}

func (x *DryRunFileResult) GetParsedFields() map[string]string {
	if x != nil {
		return x.ParsedFields
	}
	return nil
}

func (x *DryRunFileResult) GetComposeError() string {
	if x != nil {
		return x.ComposeError
	}
	return ""
}

type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Ping
	//	*ServerMessage_ListDirectory
	//	*ServerMessage_PushRule
	//	*ServerMessage_CancelRule
	//	*ServerMessage_Credentials
	//	*ServerMessage_Revoke
	//	*ServerMessage_Ack
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ServerMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetPing() *PingCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerMessage) GetListDirectory() *ListDirectoryCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ListDirectory); ok {
			return x.ListDirectory
		}
	}
	return nil
}

func (x *ServerMessage) GetPushRule() *PushRuleCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PushRule); ok {
			return x.PushRule
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelRule() *CancelRuleCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CancelRule); ok {
			return x.CancelRule
		}
	}
	return nil
}

func (x *ServerMessage) GetCredentials() *CredentialsPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *ServerMessage) GetRevoke() *RevokeCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Revoke); ok {
			return x.Revoke
		}
	}
	return nil
}

func (x *ServerMessage) GetAck() *Acknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Ping struct {
	Ping *PingCommand `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type ServerMessage_ListDirectory struct {
	ListDirectory *ListDirectoryCommand `protobuf:"bytes,11,opt,name=list_directory,json=listDirectory,proto3,oneof"`
}

type ServerMessage_PushRule struct {
	PushRule *PushRuleCommand `protobuf:"bytes,12,opt,name=push_rule,json=pushRule,proto3,oneof"`
}

type ServerMessage_CancelRule struct {
	CancelRule *CancelRuleCommand `protobuf:"bytes,13,opt,name=cancel_rule,json=cancelRule,proto3,oneof"`
}

type ServerMessage_Credentials struct {
	Credentials *CredentialsPayload `protobuf:"bytes,14,opt,name=credentials,proto3,oneof"`
}

type ServerMessage_Revoke struct {
	Revoke *RevokeCommand `protobuf:"bytes,15,opt,name=revoke,proto3,oneof"`
}

type ServerMessage_Ack struct {
	Ack *Acknowledgement `protobuf:"bytes,16,opt,name=ack,proto3,oneof"`
}

func (*ServerMessage_Ping) isServerMessage_Payload() {}

func (*ServerMessage_ListDirectory) isServerMessage_Payload() {}

func (*ServerMessage_PushRule) isServerMessage_Payload() {}

func (*ServerMessage_CancelRule) isServerMessage_Payload() {}

func (*ServerMessage_Credentials) isServerMessage_Payload() {}

func (*ServerMessage_Revoke) isServerMessage_Payload() {}

func (*ServerMessage_Ack) isServerMessage_Payload() {}

type PingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCommand) Reset() {
	*x = PingCommand{}
	mi := &file_proto_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCommand) ProtoMessage() {}

func (x *PingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCommand.ProtoReflect.Descriptor instead.
func (*PingCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{11}
}

type ListDirectoryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	MaxDepth      int32                  `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryCommand) Reset() {
	*x = ListDirectoryCommand{}
	mi := &file_proto_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryCommand) ProtoMessage() {}

func (x *ListDirectoryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryCommand.ProtoReflect.Descriptor instead.
func (*ListDirectoryCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListDirectoryCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListDirectoryCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectoryCommand) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ListDirectoryCommand) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type PushRuleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *CollectionRule        `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRuleCommand) Reset() {
	*x = PushRuleCommand{}
	mi := &file_proto_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRuleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRuleCommand) ProtoMessage() {}

func (x *PushRuleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRuleCommand.ProtoReflect.Descriptor instead.
func (*PushRuleCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PushRuleCommand) GetRule() *CollectionRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type CollectionRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RuleId           string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode             string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	BasePath         string                 `protobuf:"bytes,4,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	PathPattern      string                 `protobuf:"bytes,5,opt,name=path_pattern,json=pathPattern,proto3" json:"path_pattern,omitempty"`
	DestPathTemplate string                 `protobuf:"bytes,6,opt,name=dest_path_template,json=destPathTemplate,proto3" json:"dest_path_template,omitempty"`
	UploadBucket     string                 `protobuf:"bytes,7,opt,name=upload_bucket,json=uploadBucket,proto3" json:"upload_bucket,omitempty"`
	Recursive        bool                   `protobuf:"varint,8,opt,name=recursive,proto3" json:"recursive,omitempty"`
	CronExpr         string                 `protobuf:"bytes,9,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	RunOnceOnStart   bool                   `protobuf:"varint,10,opt,name=run_once_on_start,json=runOnceOnStart,proto3" json:"run_once_on_start,omitempty"`
	AppendMode       string                 `protobuf:"bytes,11,opt,name=append_mode,json=appendMode,proto3" json:"append_mode,omitempty"`
	Enabled          bool                   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DryRun           bool                   `protobuf:"varint,13,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectionRule) Reset() {
	*x = CollectionRule{}
	mi := &file_proto_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionRule) ProtoMessage() {}

func (x *CollectionRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionRule.ProtoReflect.Descriptor instead.
func (*CollectionRule) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CollectionRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *CollectionRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionRule) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CollectionRule) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *CollectionRule) GetPathPattern() string {
	if x != nil {
		return x.PathPattern
	}
	return ""
}

func (x *CollectionRule) GetDestPathTemplate() string {
	if x != nil {
		return x.DestPathTemplate
	}
	return ""
}

func (x *CollectionRule) GetUploadBucket() string {
	if x != nil {
		return x.UploadBucket
	}
	return ""
}

func (x *CollectionRule) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CollectionRule) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CollectionRule) GetRunOnceOnStart() bool {
	if x != nil {
		return x.RunOnceOnStart
	}
	return false
}

func (x *CollectionRule) GetAppendMode() string {
	if x != nil {
		return x.AppendMode
	}
	return ""
}

func (x *CollectionRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CollectionRule) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type CancelRuleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRuleCommand) Reset() {
	*x = CancelRuleCommand{}
	mi := &file_proto_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRuleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRuleCommand) ProtoMessage() {}

func (x *CancelRuleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRuleCommand.ProtoReflect.Descriptor instead.
func (*CancelRuleCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CancelRuleCommand) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type CredentialsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	UseSsl        bool                   `protobuf:"varint,5,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsPayload) Reset() {
	*x = CredentialsPayload{}
	mi := &file_proto_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsPayload) ProtoMessage() {}

func (x *CredentialsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsPayload.ProtoReflect.Descriptor instead.
func (*CredentialsPayload) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CredentialsPayload) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *CredentialsPayload) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CredentialsPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *CredentialsPayload) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CredentialsPayload) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

func (x *CredentialsPayload) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RevokeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCommand) Reset() {
	*x = RevokeCommand{}
	mi := &file_proto_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCommand) ProtoMessage() {}

func (x *RevokeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCommand.ProtoReflect.Descriptor instead.
func (*RevokeCommand) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefMessageId  string                 `protobuf:"bytes,1,opt,name=ref_message_id,json=refMessageId,proto3" json:"ref_message_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_proto_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *Acknowledgement) GetRefMessageId() string {
	if x != nil {
		return x.RefMessageId
	}
	return ""
}

func (x *Acknowledgement) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Acknowledgement) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	IpAddress     string                 `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	AgentName     string                 `protobuf:"bytes,5,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type PollApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollApprovalRequest) Reset() {
	*x = PollApprovalRequest{}
	mi := &file_proto_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollApprovalRequest) ProtoMessage() {}

func (x *PollApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollApprovalRequest.ProtoReflect.Descriptor instead.
func (*PollApprovalRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PollApprovalRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PollApprovalRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type PollApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AgentName     string                 `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollApprovalResponse) Reset() {
	*x = PollApprovalResponse{}
	mi := &file_proto_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollApprovalResponse) ProtoMessage() {}

func (x *PollApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollApprovalResponse.ProtoReflect.Descriptor instead.
func (*PollApprovalResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *PollApprovalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PollApprovalResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *PollApprovalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PollApprovalResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type RefreshCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCredentialsRequest) Reset() {
	*x = RefreshCredentialsRequest{}
	mi := &file_proto_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCredentialsRequest) ProtoMessage() {}

func (x *RefreshCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RefreshCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *RefreshCredentialsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RefreshCredentialsRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type RefreshCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *CredentialsPayload    `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCredentialsResponse) Reset() {
	*x = RefreshCredentialsResponse{}
	mi := &file_proto_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCredentialsResponse) ProtoMessage() {}

func (x *RefreshCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RefreshCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *RefreshCredentialsResponse) GetCredentials() *CredentialsPayload {
	if x != nil {
		return x.Credentials
	}
	return nil
}

var File_v1_agent_proto protoreflect.FileDescriptor

const file_proto_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/agent.proto\x12\ffileagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x03\n" +
	"\fAgentMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x127\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x17.fileagent.v1.HeartbeatH\x00R\theartbeat\x12A\n" +
	"\rupload_result\x18\v \x01(\v2\x1a.fileagent.v1.UploadResultH\x00R\fuploadResult\x12M\n" +
	"\x11directory_listing\x18\f \x01(\v2\x1e.fileagent.v1.DirectoryListingH\x00R\x10directoryListing\x12A\n" +
	"\vrule_status\x18\r \x01(\v2\x1e.fileagent.v1.RuleStatusReportH\x00R\n" +
	"ruleStatus\x12>\n" +
	"\ferror_report\x18\x0e \x01(\v2\x19.fileagent.v1.ErrorReportH\x00R\verrorReport\x12B\n" +
	"\x0edry_run_result\x18\x0f \x01(\v2\x1a.fileagent.v1.DryRunResultH\x00R\fdryRunResultB\t\n" +
	"\apayload\"\xd5\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vqueue_depth\x18\x03 \x01(\x05R\n" +
	"queueDepth\x12\x1d\n" +
	"\n" +
	"upload_bps\x18\x04 \x01(\x02R\tuploadBps\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12,\n" +
	"\x05disks\x18\x06 \x03(\v2\x16.fileagent.v1.DiskInfoR\x05disks\"w\n" +
	"\bDiskInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x04R\tfreeBytes\x12\x17\n" +
	"\afs_type\x18\x04 \x01(\tR\x06fsType\"\xa4\x03\n" +
	"\fUploadResult\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x12!\n" +
	"\fstorage_path\x18\x03 \x01(\tR\vstoragePath\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04etag\x18\a \x01(\tR\x04etag\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"file_mtime\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tfileMtime\x12;\n" +
	"\vuploaded_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\"\x8c\x01\n" +
	"\x10DirectoryListing\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12/\n" +
	"\aentries\x18\x03 \x03(\v2\x15.fileagent.v1.FsEntryR\aentries\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xb2\x01\n" +
	"\aFsEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12;\n" +
	"\vmodified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12 \n" +
	"\vpermissions\x18\x05 \x01(\tR\vpermissions\"\xb0\x01\n" +
	"\x10RuleStatusReport\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12'\n" +
	"\x0ffiles_processed\x18\x04 \x01(\x03R\x0efilesProcessed\x12%\n" +
	"\x0ebytes_uploaded\x18\x05 \x01(\x03R\rbytesUploaded\"S\n" +
	"\vErrorReport\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"s\n" +
	"\fDryRunResult\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x124\n" +
	"\x05files\x18\x02 \x03(\v2\x1e.fileagent.v1.DryRunFileResultR\x05files\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8f\x02\n" +
	"\x10DryRunFileResult\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vupload_path\x18\x02 \x01(\tR\n" +
	"uploadPath\x12U\n" +
	"\rparsed_fields\x18\x03 \x03(\v20.fileagent.v1.DryRunFileResult.ParsedFieldsEntryR\fparsedFields\x12#\n" +
	"\rcompose_error\x18\x04 \x01(\tR\fcomposeError\x1a?\n" +
	"\x11ParsedFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x03\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12/\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x19.fileagent.v1.PingCommandH\x00R\x04ping\x12K\n" +
	"\x0elist_directory\x18\v \x01(\v2\".fileagent.v1.ListDirectoryCommandH\x00R\rlistDirectory\x12<\n" +
	"\tpush_rule\x18\f \x01(\v2\x1d.fileagent.v1.PushRuleCommandH\x00R\bpushRule\x12B\n" +
	"\vcancel_rule\x18\r \x01(\v2\x1f.fileagent.v1.CancelRuleCommandH\x00R\n" +
	"cancelRule\x12D\n" +
	"\vcredentials\x18\x0e \x01(\v2 .fileagent.v1.CredentialsPayloadH\x00R\vcredentials\x125\n" +
	"\x06revoke\x18\x0f \x01(\v2\x1b.fileagent.v1.RevokeCommandH\x00R\x06revoke\x121\n" +
	"\x03ack\x18\x10 \x01(\v2\x1d.fileagent.v1.AcknowledgementH\x00R\x03ackB\t\n" +
	"\apayload\"\r\n" +
	"\vPingCommand\"\x84\x01\n" +
	"\x14ListDirectoryCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12\x1b\n" +
	"\tmax_depth\x18\x04 \x01(\x05R\bmaxDepth\"C\n" +
	"\x0fPushRuleCommand\x120\n" +
	"\x04rule\x18\x01 \x01(\v2\x1c.fileagent.v1.CollectionRuleR\x04rule\"\x9e\x03\n" +
	"\x0eCollectionRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1b\n" +
	"\tbase_path\x18\x04 \x01(\tR\bbasePath\x12!\n" +
	"\fpath_pattern\x18\x05 \x01(\tR\vpathPattern\x12,\n" +
	"\x12dest_path_template\x18\x06 \x01(\tR\x10destPathTemplate\x12#\n" +
	"\rupload_bucket\x18\a \x01(\tR\fuploadBucket\x12\x1c\n" +
	"\trecursive\x18\b \x01(\bR\trecursive\x12\x1b\n" +
	"\tcron_expr\x18\t \x01(\tR\bcronExpr\x12)\n" +
	"\x11run_once_on_start\x18\n" +
	" \x01(\bR\x0erunOnceOnStart\x12\x1f\n" +
	"\vappend_mode\x18\v \x01(\tR\n" +
	"appendMode\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\x12\x17\n" +
	"\adry_run\x18\r \x01(\bR\x06dryRun\",\n" +
	"\x11CancelRuleCommand\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"\xe7\x01\n" +
	"\x12CredentialsPayload\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x17\n" +
	"\ause_ssl\x18\x05 \x01(\bR\x06useSsl\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"'\n" +
	"\rRevokeCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"g\n" +
	"\x0fAcknowledgement\x12$\n" +
	"\x0eref_message_id\x18\x01 \x01(\tR\frefMessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xdf\x01\n" +
	"\x0fRegisterRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\"\x9d\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x05 \x01(\tR\tagentName\"R\n" +
	"\x13PollApprovalRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\"\x86\x01\n" +
	"\x14PollApprovalResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\"O\n" +
	"\x19RefreshCredentialsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\"`\n" +
	"\x1aRefreshCredentialsResponse\x12B\n" +
	"\vcredentials\x18\x01 \x01(\v2 .fileagent.v1.CredentialsPayloadR\vcredentials2\xe1\x02\n" +
	"\fAgentService\x12F\n" +
	"\aConnect\x12\x1a.fileagent.v1.AgentMessage\x1a\x1b.fileagent.v1.ServerMessage(\x010\x01\x12I\n" +
	"\bRegister\x12\x1d.fileagent.v1.RegisterRequest\x1a\x1e.fileagent.v1.RegisterResponse\x12U\n" +
	"\fPollApproval\x12!.fileagent.v1.PollApprovalRequest\x1a\".fileagent.v1.PollApprovalResponse\x12g\n" +
	"\x12RefreshCredentials\x12'.fileagent.v1.RefreshCredentialsRequest\x1a(.fileagent.v1.RefreshCredentialsResponseB-Z+github.com/byw-dev/fileagent/api/v1;agentv1b\x06proto3"

var (
	file_proto_v1_agent_proto_rawDescOnce sync.Once
	file_proto_v1_agent_proto_rawDescData []byte
)

func file_proto_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_agent_proto_rawDesc), len(file_proto_v1_agent_proto_rawDesc)))
	})
	return file_proto_v1_agent_proto_rawDescData
}

var file_proto_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),               // 0: fileagent.v1.AgentMessage
	(*Heartbeat)(nil),                  // 1: fileagent.v1.Heartbeat
	(*DiskInfo)(nil),                   // 2: fileagent.v1.DiskInfo
	(*UploadResult)(nil),               // 3: fileagent.v1.UploadResult
	(*DirectoryListing)(nil),           // 4: fileagent.v1.DirectoryListing
	(*FsEntry)(nil),                    // 5: fileagent.v1.FsEntry
	(*RuleStatusReport)(nil),           // 6: fileagent.v1.RuleStatusReport
	(*ErrorReport)(nil),                // 7: fileagent.v1.ErrorReport
	(*DryRunResult)(nil),               // 8: fileagent.v1.DryRunResult
	(*DryRunFileResult)(nil),           // 9: fileagent.v1.DryRunFileResult
	(*ServerMessage)(nil),              // 10: fileagent.v1.ServerMessage
	(*PingCommand)(nil),                // 11: fileagent.v1.PingCommand
	(*ListDirectoryCommand)(nil),       // 12: fileagent.v1.ListDirectoryCommand
	(*PushRuleCommand)(nil),            // 13: fileagent.v1.PushRuleCommand
	(*CollectionRule)(nil),             // 14: fileagent.v1.CollectionRule
	(*CancelRuleCommand)(nil),          // 15: fileagent.v1.CancelRuleCommand
	(*CredentialsPayload)(nil),         // 16: fileagent.v1.CredentialsPayload
	(*RevokeCommand)(nil),              // 17: fileagent.v1.RevokeCommand
	(*Acknowledgement)(nil),            // 18: fileagent.v1.Acknowledgement
	(*RegisterRequest)(nil),            // 19: fileagent.v1.RegisterRequest
	(*RegisterResponse)(nil),           // 20: fileagent.v1.RegisterResponse
	(*PollApprovalRequest)(nil),        // 21: fileagent.v1.PollApprovalRequest
	(*PollApprovalResponse)(nil),       // 22: fileagent.v1.PollApprovalResponse
	(*RefreshCredentialsRequest)(nil),  // 23: fileagent.v1.RefreshCredentialsRequest
	(*RefreshCredentialsResponse)(nil), // 24: fileagent.v1.RefreshCredentialsResponse
	nil,                                // 25: fileagent.v1.DryRunFileResult.ParsedFieldsEntry
	(*timestamppb.Timestamp)(nil),      // 26: google.protobuf.Timestamp
}
var file_proto_v1_agent_proto_depIdxs = []int32{
	1,  // 0: fileagent.v1.AgentMessage.heartbeat:type_name -> fileagent.v1.Heartbeat
	3,  // 1: fileagent.v1.AgentMessage.upload_result:type_name -> fileagent.v1.UploadResult
	4,  // 2: fileagent.v1.AgentMessage.directory_listing:type_name -> fileagent.v1.DirectoryListing
	6,  // 3: fileagent.v1.AgentMessage.rule_status:type_name -> fileagent.v1.RuleStatusReport
	7,  // 4: fileagent.v1.AgentMessage.error_report:type_name -> fileagent.v1.ErrorReport
	8,  // 5: fileagent.v1.AgentMessage.dry_run_result:type_name -> fileagent.v1.DryRunResult
	2,  // 6: fileagent.v1.Heartbeat.disks:type_name -> fileagent.v1.DiskInfo
	26, // 7: fileagent.v1.UploadResult.file_mtime:type_name -> google.protobuf.Timestamp
	26, // 8: fileagent.v1.UploadResult.uploaded_at:type_name -> google.protobuf.Timestamp
	5,  // 9: fileagent.v1.DirectoryListing.entries:type_name -> fileagent.v1.FsEntry
	26, // 10: fileagent.v1.FsEntry.modified_at:type_name -> google.protobuf.Timestamp
	9,  // 11: fileagent.v1.DryRunResult.files:type_name -> fileagent.v1.DryRunFileResult
	25, // 12: fileagent.v1.DryRunFileResult.parsed_fields:type_name -> fileagent.v1.DryRunFileResult.ParsedFieldsEntry
	11, // 13: fileagent.v1.ServerMessage.ping:type_name -> fileagent.v1.PingCommand
	12, // 14: fileagent.v1.ServerMessage.list_directory:type_name -> fileagent.v1.ListDirectoryCommand
	13, // 15: fileagent.v1.ServerMessage.push_rule:type_name -> fileagent.v1.PushRuleCommand
	15, // 16: fileagent.v1.ServerMessage.cancel_rule:type_name -> fileagent.v1.CancelRuleCommand
	16, // 17: fileagent.v1.ServerMessage.credentials:type_name -> fileagent.v1.CredentialsPayload
	17, // 18: fileagent.v1.ServerMessage.revoke:type_name -> fileagent.v1.RevokeCommand
	18, // 19: fileagent.v1.ServerMessage.ack:type_name -> fileagent.v1.Acknowledgement
	14, // 20: fileagent.v1.PushRuleCommand.rule:type_name -> fileagent.v1.CollectionRule
	26, // 21: fileagent.v1.CredentialsPayload.expires_at:type_name -> google.protobuf.Timestamp
	16, // 22: fileagent.v1.RefreshCredentialsResponse.credentials:type_name -> fileagent.v1.CredentialsPayload
	0,  // 23: fileagent.v1.AgentService.Connect:input_type -> fileagent.v1.AgentMessage
	19, // 24: fileagent.v1.AgentService.Register:input_type -> fileagent.v1.RegisterRequest
	21, // 25: fileagent.v1.AgentService.PollApproval:input_type -> fileagent.v1.PollApprovalRequest
	23, // 26: fileagent.v1.AgentService.RefreshCredentials:input_type -> fileagent.v1.RefreshCredentialsRequest
	10, // 27: fileagent.v1.AgentService.Connect:output_type -> fileagent.v1.ServerMessage
	20, // 28: fileagent.v1.AgentService.Register:output_type -> fileagent.v1.RegisterResponse
	22, // 29: fileagent.v1.AgentService.PollApproval:output_type -> fileagent.v1.PollApprovalResponse
	24, // 30: fileagent.v1.AgentService.RefreshCredentials:output_type -> fileagent.v1.RefreshCredentialsResponse
	27, // [27:31] is the sub-list for method output_type
	23, // [23:27] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_v1_agent_proto_init() }
func file_proto_v1_agent_proto_init() {
	if File_v1_agent_proto != nil {
		return
	}
	file_proto_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_UploadResult)(nil),
		(*AgentMessage_DirectoryListing)(nil),
		(*AgentMessage_RuleStatus)(nil),
		(*AgentMessage_ErrorReport)(nil),
		(*AgentMessage_DryRunResult)(nil),
	}
	file_proto_v1_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_ListDirectory)(nil),
		(*ServerMessage_PushRule)(nil),
		(*ServerMessage_CancelRule)(nil),
		(*ServerMessage_Credentials)(nil),
		(*ServerMessage_Revoke)(nil),
		(*ServerMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_agent_proto_rawDesc), len(file_proto_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_v1_agent_proto_msgTypes,
	}.Build()
	File_v1_agent_proto = out.File
	file_proto_v1_agent_proto_goTypes = nil
	file_proto_v1_agent_proto_depIdxs = nil
}
