// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    org_id,
    name,
    fingerprint,
    os_info,
    ip_address,
    status
) VALUES (
    $1, $2, $3, $4, $5, 'pending'
)
RETURNING id, org_id, name, fingerprint, status, auth_token_hash, token_expires_at, os_info, ip_address, approved_by, approved_at, revoked_by, revoked_at, last_seen_at, metadata, created_at, updated_at
`

type CreateAgentParams struct {
	OrgID       uuid.UUID       `db:"org_id" json:"org_id"`
	Name        string          `db:"name" json:"name"`
	Fingerprint string          `db:"fingerprint" json:"fingerprint"`
	OsInfo      json.RawMessage `db:"os_info" json:"os_info"`
	IpAddress   pqtype.Inet     `db:"ip_address" json:"ip_address"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (*Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.OrgID,
		arg.Name,
		arg.Fingerprint,
		arg.OsInfo,
		arg.IpAddress,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Fingerprint,
		&i.Status,
		&i.AuthTokenHash,
		&i.TokenExpiresAt,
		&i.OsInfo,
		&i.IpAddress,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgentByFingerprint = `-- name: GetAgentByFingerprint :one
SELECT id, org_id, name, fingerprint, status, auth_token_hash, token_expires_at, os_info, ip_address, approved_by, approved_at, revoked_by, revoked_at, last_seen_at, metadata, created_at, updated_at FROM agents
WHERE fingerprint = $1
LIMIT 1
`

func (q *Queries) GetAgentByFingerprint(ctx context.Context, fingerprint string) (*Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByFingerprint, fingerprint)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Fingerprint,
		&i.Status,
		&i.AuthTokenHash,
		&i.TokenExpiresAt,
		&i.OsInfo,
		&i.IpAddress,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, org_id, name, fingerprint, status, auth_token_hash, token_expires_at, os_info, ip_address, approved_by, approved_at, revoked_by, revoked_at, last_seen_at, metadata, created_at, updated_at FROM agents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (*Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Fingerprint,
		&i.Status,
		&i.AuthTokenHash,
		&i.TokenExpiresAt,
		&i.OsInfo,
		&i.IpAddress,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, org_id, name, fingerprint, status, auth_token_hash, token_expires_at, os_info, ip_address, approved_by, approved_at, revoked_by, revoked_at, last_seen_at, metadata, created_at, updated_at FROM agents
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAgents(ctx context.Context, orgID uuid.UUID) ([]*Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Fingerprint,
			&i.Status,
			&i.AuthTokenHash,
			&i.TokenExpiresAt,
			&i.OsInfo,
			&i.IpAddress,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RevokedBy,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByStatus = `-- name: ListAgentsByStatus :many
SELECT id, org_id, name, fingerprint, status, auth_token_hash, token_expires_at, os_info, ip_address, approved_by, approved_at, revoked_by, revoked_at, last_seen_at, metadata, created_at, updated_at FROM agents
WHERE org_id = $1
  AND status = $2
ORDER BY created_at DESC
`

func (q *Queries) ListAgentsByStatus(ctx context.Context, orgID uuid.UUID, status AgentStatus) ([]*Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByStatus, orgID, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Fingerprint,
			&i.Status,
			&i.AuthTokenHash,
			&i.TokenExpiresAt,
			&i.OsInfo,
			&i.IpAddress,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RevokedBy,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentAuthToken = `-- name: UpdateAgentAuthToken :one
UPDATE agents
SET auth_token_hash = $2,
    token_expires_at = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, fingerprint, status, auth_token_hash, token_expires_at, os_info, ip_address, approved_by, approved_at, revoked_by, revoked_at, last_seen_at, metadata, created_at, updated_at
`

func (q *Queries) UpdateAgentAuthToken(ctx context.Context, iD uuid.UUID, authTokenHash sql.NullString, tokenExpiresAt sql.NullTime) (*Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgentAuthToken, iD, authTokenHash, tokenExpiresAt)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Fingerprint,
		&i.Status,
		&i.AuthTokenHash,
		&i.TokenExpiresAt,
		&i.OsInfo,
		&i.IpAddress,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateAgentLastSeen = `-- name: UpdateAgentLastSeen :exec
UPDATE agents
SET last_seen_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// UpdateAgentLastSeen updates last_seen_at and updated_at for the given agent
// without touching the IP address column.
func (q *Queries) UpdateAgentLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAgentLastSeen, id)
	return err
}

const updateAgentHeartbeat = `-- name: UpdateAgentHeartbeat :exec
UPDATE agents
SET last_seen_at = NOW(),
    ip_address = $2,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAgentHeartbeat(ctx context.Context, iD uuid.UUID, ipAddress pqtype.Inet) error {
	_, err := q.db.ExecContext(ctx, updateAgentHeartbeat, iD, ipAddress)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE agents
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, fingerprint, status, auth_token_hash, token_expires_at, os_info, ip_address, approved_by, approved_at, revoked_by, revoked_at, last_seen_at, metadata, created_at, updated_at
`

func (q *Queries) UpdateAgentStatus(ctx context.Context, iD uuid.UUID, status AgentStatus) (*Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgentStatus, iD, status)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Fingerprint,
		&i.Status,
		&i.AuthTokenHash,
		&i.TokenExpiresAt,
		&i.OsInfo,
		&i.IpAddress,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedBy,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const markAgentOfflineIfOnline = `-- name: MarkAgentOfflineIfOnline :execrows
UPDATE agents
SET status = 'offline',
    updated_at = NOW()
WHERE id = $1 AND status = 'online'
`

// Transition an agent to offline only when it is currently online. Returns the
// number of rows affected (1 = actually transitioned, 0 = already offline or
// gone), so a caller such as the offline sweeper can publish
// events.agent.offline exactly once and avoid double-firing when the gRPC
// disconnect path already marked the agent offline.
func (q *Queries) MarkAgentOfflineIfOnline(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentOfflineIfOnline, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
