// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buckets.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (org_id, name, description, policy_json, sts_role_arn)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, description, policy_json, sts_role_arn, created_at, updated_at
`

type CreateBucketParams struct {
	OrgID       uuid.UUID             `db:"org_id" json:"org_id"`
	Name        string                `db:"name" json:"name"`
	Description sql.NullString        `db:"description" json:"description"`
	PolicyJson  pqtype.NullRawMessage `db:"policy_json" json:"policy_json"`
	StsRoleArn  sql.NullString        `db:"sts_role_arn" json:"sts_role_arn"`
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (*Bucket, error) {
	row := q.db.QueryRowContext(ctx, createBucket,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.PolicyJson,
		arg.StsRoleArn,
	)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.PolicyJson,
		&i.StsRoleArn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getBucketByID = `-- name: GetBucketByID :one
SELECT id, org_id, name, description, policy_json, sts_role_arn, created_at, updated_at
FROM buckets
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBucketByID(ctx context.Context, id uuid.UUID) (*Bucket, error) {
	row := q.db.QueryRowContext(ctx, getBucketByID, id)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.PolicyJson,
		&i.StsRoleArn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT id, org_id, name, description, policy_json, sts_role_arn, created_at, updated_at
FROM buckets
WHERE org_id = $1
ORDER BY name ASC
`

func (q *Queries) ListBuckets(ctx context.Context, orgID uuid.UUID) ([]*Bucket, error) {
	rows, err := q.db.QueryContext(ctx, listBuckets, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Bucket{}
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.PolicyJson,
			&i.StsRoleArn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
