// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deadletter.sql

package db

import (
	"context"
	"database/sql"
)

const countDeadLetters = `-- name: CountDeadLetters :one
SELECT count(*) FROM webhook_dead_letters
`

func (q *Queries) CountDeadLetters(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeadLetters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeadLetter = `-- name: DeleteDeadLetter :exec
DELETE FROM webhook_dead_letters WHERE dedup_key = $1
`

func (q *Queries) DeleteDeadLetter(ctx context.Context, dedupKey string) error {
	_, err := q.db.ExecContext(ctx, deleteDeadLetter, dedupKey)
	return err
}

const upsertDeadLetter = `-- name: UpsertDeadLetter :one

INSERT INTO webhook_dead_letters (
    dedup_key, event_name, bucket, key,
    size_bytes, etag, observed_at, event_seq,
    fail_count, last_error, active
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
ON CONFLICT (dedup_key) DO UPDATE SET
    event_name  = EXCLUDED.event_name,
    bucket      = EXCLUDED.bucket,
    key         = EXCLUDED.key,
    size_bytes  = EXCLUDED.size_bytes,
    etag        = EXCLUDED.etag,
    observed_at = EXCLUDED.observed_at,
    event_seq   = EXCLUDED.event_seq,
    fail_count  = EXCLUDED.fail_count,
    last_error  = EXCLUDED.last_error,
    active      = EXCLUDED.active,
    updated_at  = now()
RETURNING id, dedup_key, event_name, bucket, key, size_bytes, etag, observed_at, event_seq, fail_count, last_error, active, created_at, updated_at
`

type UpsertDeadLetterParams struct {
	DedupKey   string         `db:"dedup_key" json:"dedup_key"`
	EventName  string         `db:"event_name" json:"event_name"`
	Bucket     string         `db:"bucket" json:"bucket"`
	Key        string         `db:"key" json:"key"`
	SizeBytes  int64          `db:"size_bytes" json:"size_bytes"`
	Etag       sql.NullString `db:"etag" json:"etag"`
	ObservedAt sql.NullTime   `db:"observed_at" json:"observed_at"`
	EventSeq   sql.NullString `db:"event_seq" json:"event_seq"`
	FailCount  int32          `db:"fail_count" json:"fail_count"`
	LastError  sql.NullString `db:"last_error" json:"last_error"`
	Active     bool           `db:"active" json:"active"`
}

// IC-4a: dead-letter storage for MinIO webhook events that exhausted the
// poison-pill retry cap (IC-BUG-6). Redrive is operator-driven; see the
// migration header and docs/design/consistency-and-ingest.md §3.7.
func (q *Queries) UpsertDeadLetter(ctx context.Context, arg UpsertDeadLetterParams) (*WebhookDeadLetter, error) {
	row := q.db.QueryRowContext(ctx, upsertDeadLetter,
		arg.DedupKey,
		arg.EventName,
		arg.Bucket,
		arg.Key,
		arg.SizeBytes,
		arg.Etag,
		arg.ObservedAt,
		arg.EventSeq,
		arg.FailCount,
		arg.LastError,
		arg.Active,
	)
	var i WebhookDeadLetter
	err := row.Scan(
		&i.ID,
		&i.DedupKey,
		&i.EventName,
		&i.Bucket,
		&i.Key,
		&i.SizeBytes,
		&i.Etag,
		&i.ObservedAt,
		&i.EventSeq,
		&i.FailCount,
		&i.LastError,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
