// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_rules.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createEventRule = `-- name: CreateEventRule :one
INSERT INTO event_rules (org_id, name, event_type, filter, action_type, action_config, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, event_type, filter, action_type, action_config, enabled, created_by, created_at, updated_at
`

type CreateEventRuleParams struct {
	OrgID        uuid.UUID       `db:"org_id" json:"org_id"`
	Name         string          `db:"name" json:"name"`
	EventType    EventType       `db:"event_type" json:"event_type"`
	Filter       json.RawMessage `db:"filter" json:"filter"`
	ActionType   ActionType      `db:"action_type" json:"action_type"`
	ActionConfig json.RawMessage `db:"action_config" json:"action_config"`
	Enabled      bool            `db:"enabled" json:"enabled"`
	CreatedBy    uuid.NullUUID   `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateEventRule(ctx context.Context, arg CreateEventRuleParams) (*EventRule, error) {
	row := q.db.QueryRowContext(ctx, createEventRule,
		arg.OrgID,
		arg.Name,
		arg.EventType,
		arg.Filter,
		arg.ActionType,
		arg.ActionConfig,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i EventRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.EventType,
		&i.Filter,
		&i.ActionType,
		&i.ActionConfig,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteEventRule = `-- name: DeleteEventRule :exec
DELETE FROM event_rules WHERE id = $1
`

func (q *Queries) DeleteEventRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEventRule, id)
	return err
}

const getEventRuleByID = `-- name: GetEventRuleByID :one
SELECT id, org_id, name, event_type, filter, action_type, action_config, enabled, created_by, created_at, updated_at
FROM event_rules
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEventRuleByID(ctx context.Context, id uuid.UUID) (*EventRule, error) {
	row := q.db.QueryRowContext(ctx, getEventRuleByID, id)
	var i EventRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.EventType,
		&i.Filter,
		&i.ActionType,
		&i.ActionConfig,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listEventRules = `-- name: ListEventRules :many
SELECT id, org_id, name, event_type, filter, action_type, action_config, enabled, created_by, created_at, updated_at
FROM event_rules
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEventRules(ctx context.Context, orgID uuid.UUID) ([]*EventRule, error) {
	rows, err := q.db.QueryContext(ctx, listEventRules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventRule{}
	for rows.Next() {
		var i EventRule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.EventType,
			&i.Filter,
			&i.ActionType,
			&i.ActionConfig,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventRule = `-- name: UpdateEventRule :one
UPDATE event_rules
SET name          = $2,
    event_type    = $3,
    filter        = $4,
    action_type   = $5,
    action_config = $6,
    enabled       = $7,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, org_id, name, event_type, filter, action_type, action_config, enabled, created_by, created_at, updated_at
`

type UpdateEventRuleParams struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	Name         string          `db:"name" json:"name"`
	EventType    EventType       `db:"event_type" json:"event_type"`
	Filter       json.RawMessage `db:"filter" json:"filter"`
	ActionType   ActionType      `db:"action_type" json:"action_type"`
	ActionConfig json.RawMessage `db:"action_config" json:"action_config"`
	Enabled      bool            `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateEventRule(ctx context.Context, arg UpdateEventRuleParams) (*EventRule, error) {
	row := q.db.QueryRowContext(ctx, updateEventRule,
		arg.ID,
		arg.Name,
		arg.EventType,
		arg.Filter,
		arg.ActionType,
		arg.ActionConfig,
		arg.Enabled,
	)
	var i EventRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.EventType,
		&i.Filter,
		&i.ActionType,
		&i.ActionConfig,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
