// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_type_rules.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFileTypeRule = `-- name: CreateFileTypeRule :one
INSERT INTO file_type_rules (file_type_id, path_pattern, priority)
VALUES ($1, $2, $3)
RETURNING id, file_type_id, path_pattern, priority, created_at
`

func (q *Queries) CreateFileTypeRule(ctx context.Context, fileTypeID uuid.UUID, pathPattern string, priority int32) (*FileTypeRule, error) {
	row := q.db.QueryRowContext(ctx, createFileTypeRule, fileTypeID, pathPattern, priority)
	var i FileTypeRule
	err := row.Scan(
		&i.ID,
		&i.FileTypeID,
		&i.PathPattern,
		&i.Priority,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteFileTypeRulesByFileTypeID = `-- name: DeleteFileTypeRulesByFileTypeID :exec
DELETE FROM file_type_rules WHERE file_type_id = $1
`

func (q *Queries) DeleteFileTypeRulesByFileTypeID(ctx context.Context, fileTypeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFileTypeRulesByFileTypeID, fileTypeID)
	return err
}

const listFileTypeRulesByFileTypeID = `-- name: ListFileTypeRulesByFileTypeID :many
SELECT id, file_type_id, path_pattern, priority, created_at
FROM file_type_rules
WHERE file_type_id = $1
ORDER BY priority DESC
`

func (q *Queries) ListFileTypeRulesByFileTypeID(ctx context.Context, fileTypeID uuid.UUID) ([]*FileTypeRule, error) {
	rows, err := q.db.QueryContext(ctx, listFileTypeRulesByFileTypeID, fileTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FileTypeRule{}
	for rows.Next() {
		var i FileTypeRule
		if err := rows.Scan(
			&i.ID,
			&i.FileTypeID,
			&i.PathPattern,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
