// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_entries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFileEntryByID = `-- name: GetFileEntryByID :one
SELECT id, org_id, file_type_id, agent_id, rule_id, bucket_id, storage_path, original_path, file_name, size_bytes, sha256, etag, content_type, file_mtime, status, uploaded_at, created_at, updated_at, observed_at, source, event_seq, meta_incomplete FROM file_entries WHERE id=$1 LIMIT 1
`

func (q *Queries) GetFileEntryByID(ctx context.Context, id uuid.UUID) (*FileEntry, error) {
	row := q.db.QueryRowContext(ctx, getFileEntryByID, id)
	var i FileEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FileTypeID,
		&i.AgentID,
		&i.RuleID,
		&i.BucketID,
		&i.StoragePath,
		&i.OriginalPath,
		&i.FileName,
		&i.SizeBytes,
		&i.Sha256,
		&i.Etag,
		&i.ContentType,
		&i.FileMtime,
		&i.Status,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Source,
		&i.EventSeq,
		&i.MetaIncomplete,
	)
	return &i, err
}

const listFileEntriesBase = `-- name: ListFileEntriesBase :many
SELECT id, org_id, file_type_id, agent_id, rule_id, bucket_id,
       storage_path, original_path, file_name, size_bytes,
       sha256, etag, content_type, file_mtime, status, uploaded_at,
       created_at, updated_at, observed_at, source, event_seq, meta_incomplete
FROM file_entries
WHERE org_id = $1
  AND ($2::UUID IS NULL OR agent_id = $2)
  AND ($3::UUID IS NULL OR bucket_id = $3)
  AND ($4::UUID IS NULL OR file_type_id = $4)
  AND ($5::file_status IS NULL OR status = $5)
  AND ($6::TIMESTAMPTZ IS NULL OR (created_at, id) < ($6, $7::UUID))
`

type ListFileEntriesBaseParams struct {
	OrgID   uuid.UUID  `db:"org_id" json:"org_id"`
	Column2 uuid.UUID  `db:"column_2" json:"column_2"`
	Column3 uuid.UUID  `db:"column_3" json:"column_3"`
	Column4 uuid.UUID  `db:"column_4" json:"column_4"`
	Column5 FileStatus `db:"column_5" json:"column_5"`
	Column6 time.Time  `db:"column_6" json:"column_6"`
	Column7 uuid.UUID  `db:"column_7" json:"column_7"`
}

func (q *Queries) ListFileEntriesBase(ctx context.Context, arg ListFileEntriesBaseParams) ([]*FileEntry, error) {
	rows, err := q.db.QueryContext(ctx, listFileEntriesBase,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FileEntry{}
	for rows.Next() {
		var i FileEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.FileTypeID,
			&i.AgentID,
			&i.RuleID,
			&i.BucketID,
			&i.StoragePath,
			&i.OriginalPath,
			&i.FileName,
			&i.SizeBytes,
			&i.Sha256,
			&i.Etag,
			&i.ContentType,
			&i.FileMtime,
			&i.Status,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservedAt,
			&i.Source,
			&i.EventSeq,
			&i.MetaIncomplete,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
