// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_types.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFileType = `-- name: CreateFileType :one
INSERT INTO file_types (org_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, description, created_by, created_at
`

func (q *Queries) CreateFileType(ctx context.Context, orgID uuid.UUID, name string, description sql.NullString, createdBy uuid.NullUUID) (*FileType, error) {
	row := q.db.QueryRowContext(ctx, createFileType,
		orgID,
		name,
		description,
		createdBy,
	)
	var i FileType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteFileType = `-- name: DeleteFileType :exec
DELETE FROM file_types WHERE id = $1
`

func (q *Queries) DeleteFileType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFileType, id)
	return err
}

const getFileTypeByID = `-- name: GetFileTypeByID :one
SELECT id, org_id, name, description, created_by, created_at
FROM file_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFileTypeByID(ctx context.Context, id uuid.UUID) (*FileType, error) {
	row := q.db.QueryRowContext(ctx, getFileTypeByID, id)
	var i FileType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getFileTypeByName = `-- name: GetFileTypeByName :one
SELECT id, org_id, name, description, created_by, created_at
FROM file_types
WHERE org_id = $1 AND name = $2
LIMIT 1
`

func (q *Queries) GetFileTypeByName(ctx context.Context, orgID uuid.UUID, name string) (*FileType, error) {
	row := q.db.QueryRowContext(ctx, getFileTypeByName, orgID, name)
	var i FileType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const listFileTypes = `-- name: ListFileTypes :many
SELECT id, org_id, name, description, created_by, created_at
FROM file_types
WHERE org_id = $1
ORDER BY name ASC
`

func (q *Queries) ListFileTypes(ctx context.Context, orgID uuid.UUID) ([]*FileType, error) {
	rows, err := q.db.QueryContext(ctx, listFileTypes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FileType{}
	for rows.Next() {
		var i FileType
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileType = `-- name: UpdateFileType :one
UPDATE file_types
SET name        = $2,
    description = $3
WHERE id = $1
RETURNING id, org_id, name, description, created_by, created_at
`

func (q *Queries) UpdateFileType(ctx context.Context, iD uuid.UUID, name string, description sql.NullString) (*FileType, error) {
	row := q.db.QueryRowContext(ctx, updateFileType, iD, name, description)
	var i FileType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}
