// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteIndexedFile = `-- name: DeleteIndexedFile :one
UPDATE file_entries AS fe
SET status = 'deleted', updated_at = now(),
    observed_at = $3, event_seq = $4, source = $5
WHERE bucket_id = $1 AND storage_path = $2
 AND ($3::timestamptz > fe.observed_at
      OR ($3::timestamptz = fe.observed_at
          AND ($4::text IS NULL OR fe.event_seq IS NULL
               OR lpad($4::text,32,'0') >= lpad(fe.event_seq,32,'0'))))
RETURNING fe.id, fe.org_id, fe.file_type_id, fe.agent_id, fe.rule_id, fe.bucket_id, fe.storage_path, fe.original_path, fe.file_name, fe.size_bytes, fe.sha256, fe.etag, fe.content_type, fe.file_mtime, fe.status, fe.uploaded_at, fe.created_at, fe.updated_at, fe.observed_at, fe.source, fe.event_seq, fe.meta_incomplete
`

type DeleteIndexedFileParams struct {
	BucketID    uuid.UUID      `db:"bucket_id" json:"bucket_id"`
	StoragePath string         `db:"storage_path" json:"storage_path"`
	ObservedAt  time.Time      `db:"observed_at" json:"observed_at"`
	EventSeq    sql.NullString `db:"event_seq" json:"event_seq"`
	Source      string         `db:"source" json:"source"`
}

func (q *Queries) DeleteIndexedFile(ctx context.Context, arg DeleteIndexedFileParams) (*FileEntry, error) {
	row := q.db.QueryRowContext(ctx, deleteIndexedFile,
		arg.BucketID,
		arg.StoragePath,
		arg.ObservedAt,
		arg.EventSeq,
		arg.Source,
	)
	var i FileEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FileTypeID,
		&i.AgentID,
		&i.RuleID,
		&i.BucketID,
		&i.StoragePath,
		&i.OriginalPath,
		&i.FileName,
		&i.SizeBytes,
		&i.Sha256,
		&i.Etag,
		&i.ContentType,
		&i.FileMtime,
		&i.Status,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Source,
		&i.EventSeq,
		&i.MetaIncomplete,
	)
	return &i, err
}

const getIndexedFileByKey = `-- name: GetIndexedFileByKey :one
SELECT id, org_id, file_type_id, agent_id, rule_id, bucket_id, storage_path, original_path, file_name, size_bytes, sha256, etag, content_type, file_mtime, status, uploaded_at, created_at, updated_at, observed_at, source, event_seq, meta_incomplete FROM file_entries WHERE bucket_id = $1 AND storage_path = $2
`

func (q *Queries) GetIndexedFileByKey(ctx context.Context, bucketID uuid.UUID, storagePath string) (*FileEntry, error) {
	row := q.db.QueryRowContext(ctx, getIndexedFileByKey, bucketID, storagePath)
	var i FileEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FileTypeID,
		&i.AgentID,
		&i.RuleID,
		&i.BucketID,
		&i.StoragePath,
		&i.OriginalPath,
		&i.FileName,
		&i.SizeBytes,
		&i.Sha256,
		&i.Etag,
		&i.ContentType,
		&i.FileMtime,
		&i.Status,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Source,
		&i.EventSeq,
		&i.MetaIncomplete,
	)
	return &i, err
}

const getIngestRuleInfo = `-- name: GetIngestRuleInfo :one
SELECT agent_id, metadata, dest_path_template FROM collection_rules
WHERE id = $1 AND org_id = $2 LIMIT 1
`

type GetIngestRuleInfoRow struct {
	AgentID          uuid.UUID       `db:"agent_id" json:"agent_id"`
	Metadata         json.RawMessage `db:"metadata" json:"metadata"`
	DestPathTemplate string          `db:"dest_path_template" json:"dest_path_template"`
}

func (q *Queries) GetIngestRuleInfo(ctx context.Context, iD uuid.UUID, orgID uuid.UUID) (*GetIngestRuleInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getIngestRuleInfo, iD, orgID)
	var i GetIngestRuleInfoRow
	err := row.Scan(&i.AgentID, &i.Metadata, &i.DestPathTemplate)
	return &i, err
}

const upsertIndexedFile = `-- name: UpsertIndexedFile :one
INSERT INTO file_entries AS fe (
    org_id, file_type_id, agent_id, rule_id, bucket_id,
    storage_path, original_path, file_name, size_bytes,
    sha256, etag, content_type, file_mtime, status, uploaded_at,
    observed_at, source, event_seq, meta_incomplete
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    CASE WHEN $16::text IN ('agent', 'api') THEN now()
         ELSE $17::timestamptz END,
    $16, $18::text, $19::boolean
)
ON CONFLICT (bucket_id, storage_path) DO UPDATE SET
    file_type_id = COALESCE(EXCLUDED.file_type_id, fe.file_type_id),
    agent_id = COALESCE(EXCLUDED.agent_id, fe.agent_id),
    rule_id = COALESCE(EXCLUDED.rule_id, fe.rule_id),
    original_path = COALESCE(EXCLUDED.original_path, fe.original_path),
    file_name = EXCLUDED.file_name,
    size_bytes = EXCLUDED.size_bytes,
    sha256 = COALESCE(EXCLUDED.sha256, fe.sha256),
    etag = COALESCE(EXCLUDED.etag, fe.etag),
    content_type = COALESCE(EXCLUDED.content_type, fe.content_type),
    file_mtime = COALESCE(EXCLUDED.file_mtime, fe.file_mtime),
    status = EXCLUDED.status,
    uploaded_at = COALESCE(EXCLUDED.uploaded_at, fe.uploaded_at),
    observed_at = EXCLUDED.observed_at,
    source = EXCLUDED.source,
    event_seq = EXCLUDED.event_seq,
    meta_incomplete = CASE WHEN EXCLUDED.source IN ('agent','api')
                           THEN EXCLUDED.meta_incomplete ELSE fe.meta_incomplete END,
    updated_at = now()
WHERE EXCLUDED.observed_at > fe.observed_at
 OR (EXCLUDED.observed_at = fe.observed_at
     AND (EXCLUDED.event_seq IS NULL OR fe.event_seq IS NULL
          OR lpad(EXCLUDED.event_seq,32,'0') >= lpad(fe.event_seq,32,'0')))
RETURNING fe.id, fe.org_id, fe.file_type_id, fe.agent_id, fe.rule_id, fe.bucket_id, fe.storage_path, fe.original_path, fe.file_name, fe.size_bytes, fe.sha256, fe.etag, fe.content_type, fe.file_mtime, fe.status, fe.uploaded_at, fe.created_at, fe.updated_at, fe.observed_at, fe.source, fe.event_seq, fe.meta_incomplete
`

type UpsertIndexedFileParams struct {
	OrgID          uuid.UUID      `db:"org_id" json:"org_id"`
	FileTypeID     uuid.NullUUID  `db:"file_type_id" json:"file_type_id"`
	AgentID        uuid.NullUUID  `db:"agent_id" json:"agent_id"`
	RuleID         uuid.NullUUID  `db:"rule_id" json:"rule_id"`
	BucketID       uuid.UUID      `db:"bucket_id" json:"bucket_id"`
	StoragePath    string         `db:"storage_path" json:"storage_path"`
	OriginalPath   sql.NullString `db:"original_path" json:"original_path"`
	FileName       string         `db:"file_name" json:"file_name"`
	SizeBytes      int64          `db:"size_bytes" json:"size_bytes"`
	Sha256         sql.NullString `db:"sha256" json:"sha256"`
	Etag           sql.NullString `db:"etag" json:"etag"`
	ContentType    sql.NullString `db:"content_type" json:"content_type"`
	FileMtime      sql.NullTime   `db:"file_mtime" json:"file_mtime"`
	Status         FileStatus     `db:"status" json:"status"`
	UploadedAt     sql.NullTime   `db:"uploaded_at" json:"uploaded_at"`
	Source         string         `db:"source" json:"source"`
	ObservedAt     time.Time      `db:"observed_at" json:"observed_at"`
	EventSeq       sql.NullString `db:"event_seq" json:"event_seq"`
	MetaIncomplete bool           `db:"meta_incomplete" json:"meta_incomplete"`
}

func (q *Queries) UpsertIndexedFile(ctx context.Context, arg UpsertIndexedFileParams) (*FileEntry, error) {
	row := q.db.QueryRowContext(ctx, upsertIndexedFile,
		arg.OrgID,
		arg.FileTypeID,
		arg.AgentID,
		arg.RuleID,
		arg.BucketID,
		arg.StoragePath,
		arg.OriginalPath,
		arg.FileName,
		arg.SizeBytes,
		arg.Sha256,
		arg.Etag,
		arg.ContentType,
		arg.FileMtime,
		arg.Status,
		arg.UploadedAt,
		arg.Source,
		arg.ObservedAt,
		arg.EventSeq,
		arg.MetaIncomplete,
	)
	var i FileEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FileTypeID,
		&i.AgentID,
		&i.RuleID,
		&i.BucketID,
		&i.StoragePath,
		&i.OriginalPath,
		&i.FileName,
		&i.SizeBytes,
		&i.Sha256,
		&i.Etag,
		&i.ContentType,
		&i.FileMtime,
		&i.Status,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.Source,
		&i.EventSeq,
		&i.MetaIncomplete,
	)
	return &i, err
}
