// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActionType string

const (
	ActionTypeWebhook      ActionType = "webhook"
	ActionTypeNatsPublish  ActionType = "nats_publish"
	ActionTypeKafkaPublish ActionType = "kafka_publish"
)

func (e *ActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActionType(s)
	case string:
		*e = ActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActionType: %T", src)
	}
	return nil
}

type NullActionType struct {
	ActionType ActionType `json:"action_type"`
	Valid      bool       `json:"valid"` // Valid is true if ActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActionType) Scan(value interface{}) error {
	if value == nil {
		ns.ActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActionType), nil
}

type AgentStatus string

const (
	AgentStatusPending  AgentStatus = "pending"
	AgentStatusApproved AgentStatus = "approved"
	AgentStatusOnline   AgentStatus = "online"
	AgentStatusOffline  AgentStatus = "offline"
	AgentStatusRevoked  AgentStatus = "revoked"
)

func (e *AgentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStatus(s)
	case string:
		*e = AgentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStatus: %T", src)
	}
	return nil
}

type NullAgentStatus struct {
	AgentStatus AgentStatus `json:"agent_status"`
	Valid       bool        `json:"valid"` // Valid is true if AgentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStatus), nil
}

type EventType string

const (
	EventTypeFileUploaded  EventType = "file_uploaded"
	EventTypeFileDeleted   EventType = "file_deleted"
	EventTypeAgentOnline   EventType = "agent_online"
	EventTypeAgentOffline  EventType = "agent_offline"
	EventTypeAgentApproved EventType = "agent_approved"
	EventTypeAgentRevoked  EventType = "agent_revoked"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"event_type"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type FileStatus string

const (
	FileStatusUploading FileStatus = "uploading"
	FileStatusCompleted FileStatus = "completed"
	FileStatusFailed    FileStatus = "failed"
	FileStatusDeleted   FileStatus = "deleted"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus `json:"file_status"`
	Valid      bool       `json:"valid"` // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type RuleStatus string

const (
	RuleStatusActive   RuleStatus = "active"
	RuleStatusInactive RuleStatus = "inactive"
)

func (e *RuleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleStatus(s)
	case string:
		*e = RuleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleStatus: %T", src)
	}
	return nil
}

type NullRuleStatus struct {
	RuleStatus RuleStatus `json:"rule_status"`
	Valid      bool       `json:"valid"` // Valid is true if RuleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RuleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleStatus), nil
}

type UploadMode string

const (
	UploadModeWatch     UploadMode = "watch"
	UploadModeScheduled UploadMode = "scheduled"
)

func (e *UploadMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadMode(s)
	case string:
		*e = UploadMode(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadMode: %T", src)
	}
	return nil
}

type NullUploadMode struct {
	UploadMode UploadMode `json:"upload_mode"`
	Valid      bool       `json:"valid"` // Valid is true if UploadMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadMode) Scan(value interface{}) error {
	if value == nil {
		ns.UploadMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadMode), nil
}

type UserRole string

const (
	UserRoleSuperAdmin UserRole = "super_admin"
	UserRoleOrgAdmin   UserRole = "org_admin"
	UserRoleOrgViewer  UserRole = "org_viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Agent struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	OrgID          uuid.UUID       `db:"org_id" json:"org_id"`
	Name           string          `db:"name" json:"name"`
	Fingerprint    string          `db:"fingerprint" json:"fingerprint"`
	Status         AgentStatus     `db:"status" json:"status"`
	AuthTokenHash  sql.NullString  `db:"auth_token_hash" json:"auth_token_hash"`
	TokenExpiresAt sql.NullTime    `db:"token_expires_at" json:"token_expires_at"`
	OsInfo         json.RawMessage `db:"os_info" json:"os_info"`
	IpAddress      pqtype.Inet     `db:"ip_address" json:"ip_address"`
	ApprovedBy     uuid.NullUUID   `db:"approved_by" json:"approved_by"`
	ApprovedAt     sql.NullTime    `db:"approved_at" json:"approved_at"`
	RevokedBy      uuid.NullUUID   `db:"revoked_by" json:"revoked_by"`
	RevokedAt      sql.NullTime    `db:"revoked_at" json:"revoked_at"`
	LastSeenAt     sql.NullTime    `db:"last_seen_at" json:"last_seen_at"`
	Metadata       json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt      time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time       `db:"updated_at" json:"updated_at"`
}

type AgentEvent struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	AgentID   uuid.UUID       `db:"agent_id" json:"agent_id"`
	EventType string          `db:"event_type" json:"event_type"`
	IpAddress pqtype.Inet     `db:"ip_address" json:"ip_address"`
	Detail    json.RawMessage `db:"detail" json:"detail"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

type Bucket struct {
	ID          uuid.UUID             `db:"id" json:"id"`
	OrgID       uuid.UUID             `db:"org_id" json:"org_id"`
	Name        string                `db:"name" json:"name"`
	Description sql.NullString        `db:"description" json:"description"`
	PolicyJson  pqtype.NullRawMessage `db:"policy_json" json:"policy_json"`
	StsRoleArn  sql.NullString        `db:"sts_role_arn" json:"sts_role_arn"`
	CreatedAt   time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time             `db:"updated_at" json:"updated_at"`
}

type CollectionRule struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	OrgID            uuid.UUID       `db:"org_id" json:"org_id"`
	AgentID          uuid.UUID       `db:"agent_id" json:"agent_id"`
	BucketID         uuid.UUID       `db:"bucket_id" json:"bucket_id"`
	Name             string          `db:"name" json:"name"`
	Mode             UploadMode      `db:"mode" json:"mode"`
	Status           RuleStatus      `db:"status" json:"status"`
	BasePath         string          `db:"base_path" json:"base_path"`
	PathPattern      string          `db:"path_pattern" json:"path_pattern"`
	DestPathTemplate string          `db:"dest_path_template" json:"dest_path_template"`
	Recursive        bool            `db:"recursive" json:"recursive"`
	CronExpr         sql.NullString  `db:"cron_expr" json:"cron_expr"`
	RunOnceOnStart   bool            `db:"run_once_on_start" json:"run_once_on_start"`
	AppendMode       string          `db:"append_mode" json:"append_mode"`
	Metadata         json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt        time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time       `db:"updated_at" json:"updated_at"`
}

type EventDelivery struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	EventRuleID  uuid.UUID       `db:"event_rule_id" json:"event_rule_id"`
	EventType    EventType       `db:"event_type" json:"event_type"`
	Payload      json.RawMessage `db:"payload" json:"payload"`
	Status       string          `db:"status" json:"status"`
	ResponseCode sql.NullInt32   `db:"response_code" json:"response_code"`
	ResponseBody sql.NullString  `db:"response_body" json:"response_body"`
	AttemptCount int32           `db:"attempt_count" json:"attempt_count"`
	NextRetryAt  sql.NullTime    `db:"next_retry_at" json:"next_retry_at"`
	CreatedAt    time.Time       `db:"created_at" json:"created_at"`
	DeliveredAt  sql.NullTime    `db:"delivered_at" json:"delivered_at"`
}

type EventRule struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	OrgID        uuid.UUID       `db:"org_id" json:"org_id"`
	Name         string          `db:"name" json:"name"`
	EventType    EventType       `db:"event_type" json:"event_type"`
	Filter       json.RawMessage `db:"filter" json:"filter"`
	ActionType   ActionType      `db:"action_type" json:"action_type"`
	ActionConfig json.RawMessage `db:"action_config" json:"action_config"`
	Enabled      bool            `db:"enabled" json:"enabled"`
	CreatedBy    uuid.NullUUID   `db:"created_by" json:"created_by"`
	CreatedAt    time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time       `db:"updated_at" json:"updated_at"`
}

type FileEntry struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	OrgID        uuid.UUID      `db:"org_id" json:"org_id"`
	FileTypeID   uuid.NullUUID  `db:"file_type_id" json:"file_type_id"`
	AgentID      uuid.NullUUID  `db:"agent_id" json:"agent_id"`
	RuleID       uuid.NullUUID  `db:"rule_id" json:"rule_id"`
	BucketID     uuid.UUID      `db:"bucket_id" json:"bucket_id"`
	StoragePath  string         `db:"storage_path" json:"storage_path"`
	OriginalPath sql.NullString `db:"original_path" json:"original_path"`
	FileName     string         `db:"file_name" json:"file_name"`
	SizeBytes    int64          `db:"size_bytes" json:"size_bytes"`
	Sha256       sql.NullString `db:"sha256" json:"sha256"`
	Etag         sql.NullString `db:"etag" json:"etag"`
	ContentType  sql.NullString `db:"content_type" json:"content_type"`
	FileMtime    sql.NullTime   `db:"file_mtime" json:"file_mtime"`
	Status       FileStatus     `db:"status" json:"status"`
	UploadedAt   sql.NullTime   `db:"uploaded_at" json:"uploaded_at"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
}

type FileType struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	OrgID       uuid.UUID      `db:"org_id" json:"org_id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedBy   uuid.NullUUID  `db:"created_by" json:"created_by"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
}

type FileTypeRule struct {
	ID          uuid.UUID `db:"id" json:"id"`
	FileTypeID  uuid.UUID `db:"file_type_id" json:"file_type_id"`
	PathPattern string    `db:"path_pattern" json:"path_pattern"`
	Priority    int32     `db:"priority" json:"priority"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type Organization struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	Name        string          `db:"name" json:"name"`
	Description sql.NullString  `db:"description" json:"description"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
}

type UploadLog struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	OrgID            uuid.UUID      `db:"org_id" json:"org_id"`
	AgentID          uuid.UUID      `db:"agent_id" json:"agent_id"`
	FileEntryID      uuid.NullUUID  `db:"file_entry_id" json:"file_entry_id"`
	RuleID           uuid.NullUUID  `db:"rule_id" json:"rule_id"`
	OriginalPath     string         `db:"original_path" json:"original_path"`
	StoragePath      string         `db:"storage_path" json:"storage_path"`
	SizeBytes        int64          `db:"size_bytes" json:"size_bytes"`
	BytesTransferred int64          `db:"bytes_transferred" json:"bytes_transferred"`
	Status           string         `db:"status" json:"status"`
	ErrorMessage     sql.NullString `db:"error_message" json:"error_message"`
	RetryCount       int32          `db:"retry_count" json:"retry_count"`
	StartedAt        time.Time      `db:"started_at" json:"started_at"`
	FinishedAt       sql.NullTime   `db:"finished_at" json:"finished_at"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	OrgID        uuid.UUID      `db:"org_id" json:"org_id"`
	Username     string         `db:"username" json:"username"`
	Email        sql.NullString `db:"email" json:"email"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	Role         UserRole       `db:"role" json:"role"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	LastLoginAt  sql.NullTime   `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
}
