// Package db provides the PostgreSQL connection pool and auto-migration runner
// for the Control Plane. It wraps database/sql with sane pool defaults and
// exposes a Queries type generated by sqlc for type-safe database access.
package db

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	// lib/pq is the PostgreSQL driver; the blank import registers it.
	_ "github.com/lib/pq"
	"go.uber.org/zap"
)

const (
	defaultMaxOpenConns    = 25
	defaultMaxIdleConns    = 10
	defaultConnMaxLifetime = 30 * time.Minute
	defaultConnMaxIdleTime = 5 * time.Minute
	defaultPingTimeout     = 5 * time.Second
)

// DB wraps *sql.DB and adds helper methods used throughout the Control Plane.
type DB struct {
	*sql.DB
	logger *zap.Logger
}

// Open opens a PostgreSQL connection pool using the provided DSN.
// It verifies connectivity with a ping before returning. The caller is
// responsible for calling Close when the DB is no longer needed.
func Open(ctx context.Context, dsn string, logger *zap.Logger) (*DB, error) {
	sqlDB, err := sql.Open("postgres", dsn)
	if err != nil {
		return nil, fmt.Errorf("db: open connection: %w", err)
	}

	// Tune the connection pool according to the system-design recommendation.
	sqlDB.SetMaxOpenConns(defaultMaxOpenConns)
	sqlDB.SetMaxIdleConns(defaultMaxIdleConns)
	sqlDB.SetConnMaxLifetime(defaultConnMaxLifetime)
	sqlDB.SetConnMaxIdleTime(defaultConnMaxIdleTime)

	db := &DB{DB: sqlDB, logger: logger}
	if err := db.ping(ctx); err != nil {
		_ = sqlDB.Close()
		return nil, err
	}

	logger.Info("database connection pool established",
		zap.Int("max_open_conns", defaultMaxOpenConns),
		zap.Int("max_idle_conns", defaultMaxIdleConns),
	)
	return db, nil
}

// Ping checks that the database is reachable within a short timeout.
func (db *DB) Ping(ctx context.Context) error {
	return db.ping(ctx)
}

func (db *DB) ping(ctx context.Context) error {
	ctx, cancel := context.WithTimeout(ctx, defaultPingTimeout)
	defer cancel()
	if err := db.DB.PingContext(ctx); err != nil {
		return fmt.Errorf("db: ping failed: %w", err)
	}
	return nil
}

// Queries returns a new *Queries bound to this DB connection, suitable for
// use in a non-transactional context.
func (db *DB) Queries() *Queries {
	return New(db.DB)
}

// WithTx executes fn inside a database transaction. If fn returns an error
// the transaction is rolled back; otherwise it is committed. The provided
// *Queries is bound to the transaction.
func (db *DB) WithTx(ctx context.Context, fn func(*Queries) error) error {
	tx, err := db.DB.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("db: begin tx: %w", err)
	}
	q := New(tx)
	if err := fn(q); err != nil {
		_ = tx.Rollback()
		return err
	}
	return tx.Commit()
}
