// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retag.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const claimNextRetagJob = `-- name: ClaimNextRetagJob :one
UPDATE retag_jobs
SET status = 'running', started_at = NOW(), attempts = attempts + 1
WHERE id = (
    SELECT id FROM retag_jobs
    WHERE status = 'pending'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, org_id, kind, spec, status, attempts, affected_count,
          last_error, actor_user_id, created_at, started_at, finished_at
`

// Atomically claim the oldest pending job, marking it running and bumping
// attempts. FOR UPDATE SKIP LOCKED keeps the claim safe if the single-instance
// assumption ever changes; today it just guarantees one drain at a time.
func (q *Queries) ClaimNextRetagJob(ctx context.Context) (*RetagJob, error) {
	row := q.db.QueryRowContext(ctx, claimNextRetagJob)
	var i RetagJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Spec,
		&i.Status,
		&i.Attempts,
		&i.AffectedCount,
		&i.LastError,
		&i.ActorUserID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const enqueueRetagJob = `-- name: EnqueueRetagJob :one
INSERT INTO retag_jobs (org_id, kind, spec, actor_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, kind, spec, status, attempts, affected_count,
          last_error, actor_user_id, created_at, started_at, finished_at
`

func (q *Queries) EnqueueRetagJob(ctx context.Context, orgID uuid.UUID, kind string, spec json.RawMessage, actorUserID uuid.NullUUID) (*RetagJob, error) {
	row := q.db.QueryRowContext(ctx, enqueueRetagJob,
		orgID,
		kind,
		spec,
		actorUserID,
	)
	var i RetagJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Spec,
		&i.Status,
		&i.Attempts,
		&i.AffectedCount,
		&i.LastError,
		&i.ActorUserID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const getRetagJob = `-- name: GetRetagJob :one
SELECT id, org_id, kind, spec, status, attempts, affected_count,
       last_error, actor_user_id, created_at, started_at, finished_at
FROM retag_jobs
WHERE id = $1 AND org_id = $2
`

func (q *Queries) GetRetagJob(ctx context.Context, iD uuid.UUID, orgID uuid.UUID) (*RetagJob, error) {
	row := q.db.QueryRowContext(ctx, getRetagJob, iD, orgID)
	var i RetagJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Spec,
		&i.Status,
		&i.Attempts,
		&i.AffectedCount,
		&i.LastError,
		&i.ActorUserID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const markRetagJobDone = `-- name: MarkRetagJobDone :exec
UPDATE retag_jobs
SET status = 'done', affected_count = $2, finished_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRetagJobDone(ctx context.Context, iD uuid.UUID, affectedCount int32) error {
	_, err := q.db.ExecContext(ctx, markRetagJobDone, iD, affectedCount)
	return err
}

const markRetagJobFailed = `-- name: MarkRetagJobFailed :exec
UPDATE retag_jobs
SET status = 'failed', last_error = $2, finished_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRetagJobFailed(ctx context.Context, iD uuid.UUID, lastError sql.NullString) error {
	_, err := q.db.ExecContext(ctx, markRetagJobFailed, iD, lastError)
	return err
}

const mergeTagValue = `-- name: MergeTagValue :execrows
WITH tk AS (
    SELECT key FROM tag_keys
    WHERE id = $5::uuid AND org_id = $1::uuid
),
updated AS (
    UPDATE file_tags ft
    SET value = $3::varchar
    FROM file_entries fe, tk
    WHERE ft.file_entry_id = fe.id
      AND fe.org_id = $1::uuid
      AND ft.key = tk.key
      AND ft.value = $2::varchar
    RETURNING ft.file_entry_id, ft.key
)
INSERT INTO tag_audit (org_id, file_entry_id, key, old_value, new_value,
                       action, actor_user_id, source)
SELECT $1::uuid, u.file_entry_id, u.key,
       $2::varchar, $3::varchar,
       'merge', $4::uuid, 'retro'
FROM updated u
`

type MergeTagValueParams struct {
	OrgID       uuid.UUID     `db:"org_id" json:"org_id"`
	FromValue   string        `db:"from_value" json:"from_value"`
	ToValue     string        `db:"to_value" json:"to_value"`
	ActorUserID uuid.NullUUID `db:"actor_user_id" json:"actor_user_id"`
	TagKeyID    uuid.UUID     `db:"tag_key_id" json:"tag_key_id"`
}

// Fold every file_tags occurrence of @from_value into the canonical @to_value
// for (org, tag key), writing one tag_audit row (action=merge, source=retro)
// per rewritten file. The key is resolved from tag_keys so org ownership is
// enforced (a corrupted spec cannot rewrite another org's tags). Idempotent: a
// re-run finds no rows still holding from_value and rewrites nothing.
func (q *Queries) MergeTagValue(ctx context.Context, arg MergeTagValueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, mergeTagValue,
		arg.OrgID,
		arg.FromValue,
		arg.ToValue,
		arg.ActorUserID,
		arg.TagKeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
