// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rules.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createCollectionRule = `-- name: CreateCollectionRule :one
INSERT INTO collection_rules (
    org_id,
    agent_id,
    bucket_id,
    name,
    mode,
    source_path_template,
    file_glob,
    upload_path_template,
    watch_recursive,
    watch_subdir_pattern,
    cron_expr,
    run_once_on_start,
    append_mode,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, org_id, agent_id, bucket_id, name, mode, status, source_path_template, file_glob, upload_path_template, watch_recursive, watch_subdir_pattern, cron_expr, run_once_on_start, append_mode, metadata, created_at, updated_at
`

type CreateCollectionRuleParams struct {
	OrgID              uuid.UUID       `db:"org_id" json:"org_id"`
	AgentID            uuid.UUID       `db:"agent_id" json:"agent_id"`
	BucketID           uuid.UUID       `db:"bucket_id" json:"bucket_id"`
	Name               string          `db:"name" json:"name"`
	Mode               UploadMode      `db:"mode" json:"mode"`
	SourcePathTemplate string          `db:"source_path_template" json:"source_path_template"`
	FileGlob           string          `db:"file_glob" json:"file_glob"`
	UploadPathTemplate string          `db:"upload_path_template" json:"upload_path_template"`
	WatchRecursive     bool            `db:"watch_recursive" json:"watch_recursive"`
	WatchSubdirPattern sql.NullString  `db:"watch_subdir_pattern" json:"watch_subdir_pattern"`
	CronExpr           sql.NullString  `db:"cron_expr" json:"cron_expr"`
	RunOnceOnStart     bool            `db:"run_once_on_start" json:"run_once_on_start"`
	AppendMode         string          `db:"append_mode" json:"append_mode"`
	Metadata           json.RawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateCollectionRule(ctx context.Context, arg CreateCollectionRuleParams) (*CollectionRule, error) {
	row := q.db.QueryRowContext(ctx, createCollectionRule,
		arg.OrgID,
		arg.AgentID,
		arg.BucketID,
		arg.Name,
		arg.Mode,
		arg.SourcePathTemplate,
		arg.FileGlob,
		arg.UploadPathTemplate,
		arg.WatchRecursive,
		arg.WatchSubdirPattern,
		arg.CronExpr,
		arg.RunOnceOnStart,
		arg.AppendMode,
		arg.Metadata,
	)
	var i CollectionRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.BucketID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.SourcePathTemplate,
		&i.FileGlob,
		&i.UploadPathTemplate,
		&i.WatchRecursive,
		&i.WatchSubdirPattern,
		&i.CronExpr,
		&i.RunOnceOnStart,
		&i.AppendMode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCollectionRule = `-- name: DeleteCollectionRule :exec
DELETE FROM collection_rules WHERE id = $1
`

func (q *Queries) DeleteCollectionRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCollectionRule, id)
	return err
}

const getCollectionRuleByID = `-- name: GetCollectionRuleByID :one
SELECT id, org_id, agent_id, bucket_id, name, mode, status, source_path_template, file_glob, upload_path_template, watch_recursive, watch_subdir_pattern, cron_expr, run_once_on_start, append_mode, metadata, created_at, updated_at FROM collection_rules
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCollectionRuleByID(ctx context.Context, id uuid.UUID) (*CollectionRule, error) {
	row := q.db.QueryRowContext(ctx, getCollectionRuleByID, id)
	var i CollectionRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.BucketID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.SourcePathTemplate,
		&i.FileGlob,
		&i.UploadPathTemplate,
		&i.WatchRecursive,
		&i.WatchSubdirPattern,
		&i.CronExpr,
		&i.RunOnceOnStart,
		&i.AppendMode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCollectionRulesByAgent = `-- name: ListCollectionRulesByAgent :many
SELECT id, org_id, agent_id, bucket_id, name, mode, status, source_path_template, file_glob, upload_path_template, watch_recursive, watch_subdir_pattern, cron_expr, run_once_on_start, append_mode, metadata, created_at, updated_at FROM collection_rules
WHERE agent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCollectionRulesByAgent(ctx context.Context, agentID uuid.UUID) ([]*CollectionRule, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionRulesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CollectionRule{}
	for rows.Next() {
		var i CollectionRule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AgentID,
			&i.BucketID,
			&i.Name,
			&i.Mode,
			&i.Status,
			&i.SourcePathTemplate,
			&i.FileGlob,
			&i.UploadPathTemplate,
			&i.WatchRecursive,
			&i.WatchSubdirPattern,
			&i.CronExpr,
			&i.RunOnceOnStart,
			&i.AppendMode,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollectionRuleStatus = `-- name: UpdateCollectionRuleStatus :one
UPDATE collection_rules
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, agent_id, bucket_id, name, mode, status, source_path_template, file_glob, upload_path_template, watch_recursive, watch_subdir_pattern, cron_expr, run_once_on_start, append_mode, metadata, created_at, updated_at
`

func (q *Queries) UpdateCollectionRuleStatus(ctx context.Context, iD uuid.UUID, status RuleStatus) (*CollectionRule, error) {
	row := q.db.QueryRowContext(ctx, updateCollectionRuleStatus, iD, status)
	var i CollectionRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.BucketID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.SourcePathTemplate,
		&i.FileGlob,
		&i.UploadPathTemplate,
		&i.WatchRecursive,
		&i.WatchSubdirPattern,
		&i.CronExpr,
		&i.RunOnceOnStart,
		&i.AppendMode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
