// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTagKey = `-- name: CreateTagKey :one
INSERT INTO tag_keys (org_id, key, label, value_controlled, required_at_collection, allow_path_var)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, key, label, value_controlled, required_at_collection,
          allow_path_var, system_reserved, created_at
`

type CreateTagKeyParams struct {
	OrgID                uuid.UUID `db:"org_id" json:"org_id"`
	Key                  string    `db:"key" json:"key"`
	Label                string    `db:"label" json:"label"`
	ValueControlled      bool      `db:"value_controlled" json:"value_controlled"`
	RequiredAtCollection bool      `db:"required_at_collection" json:"required_at_collection"`
	AllowPathVar         bool      `db:"allow_path_var" json:"allow_path_var"`
}

func (q *Queries) CreateTagKey(ctx context.Context, arg CreateTagKeyParams) (*TagKey, error) {
	row := q.db.QueryRowContext(ctx, createTagKey,
		arg.OrgID,
		arg.Key,
		arg.Label,
		arg.ValueControlled,
		arg.RequiredAtCollection,
		arg.AllowPathVar,
	)
	var i TagKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Label,
		&i.ValueControlled,
		&i.RequiredAtCollection,
		&i.AllowPathVar,
		&i.SystemReserved,
		&i.CreatedAt,
	)
	return &i, err
}

const createTagValue = `-- name: CreateTagValue :one
INSERT INTO tag_values (tag_key_id, value)
VALUES ($1, $2)
RETURNING id, tag_key_id, value, created_at
`

func (q *Queries) CreateTagValue(ctx context.Context, tagKeyID uuid.UUID, value string) (*TagValue, error) {
	row := q.db.QueryRowContext(ctx, createTagValue, tagKeyID, value)
	var i TagValue
	err := row.Scan(
		&i.ID,
		&i.TagKeyID,
		&i.Value,
		&i.CreatedAt,
	)
	return &i, err
}

const createTagValueIfAbsent = `-- name: CreateTagValueIfAbsent :execrows
INSERT INTO tag_values (tag_key_id, value)
SELECT k.id, $2 FROM tag_keys k WHERE k.id = $1 AND k.org_id = $3
ON CONFLICT (tag_key_id, value) DO NOTHING
`

// Inserts only when the tag key belongs to the org, so a corrupted pending row
// (tag_key_id pointing at another org's key) cannot promote a value cross-tenant.
func (q *Queries) CreateTagValueIfAbsent(ctx context.Context, iD uuid.UUID, value string, orgID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTagValueIfAbsent, iD, value, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingTagValue = `-- name: DeletePendingTagValue :execrows
DELETE FROM pending_tag_values WHERE id = $1 AND org_id = $2
`

func (q *Queries) DeletePendingTagValue(ctx context.Context, iD uuid.UUID, orgID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingTagValue, iD, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTagKey = `-- name: DeleteTagKey :execrows
DELETE FROM tag_keys WHERE org_id = $1 AND key = $2
`

func (q *Queries) DeleteTagKey(ctx context.Context, orgID uuid.UUID, key string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTagKey, orgID, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTagValue = `-- name: DeleteTagValue :execrows
DELETE FROM tag_values WHERE id = $1 AND tag_key_id = $2
`

func (q *Queries) DeleteTagValue(ctx context.Context, iD uuid.UUID, tagKeyID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTagValue, iD, tagKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPendingTagValue = `-- name: GetPendingTagValue :one
SELECT id, org_id, tag_key_id, extracted_value, source, source_rule_id,
       hit_count, suggested_value, status, first_seen_at
FROM pending_tag_values
WHERE id = $1 AND org_id = $2
LIMIT 1
`

func (q *Queries) GetPendingTagValue(ctx context.Context, iD uuid.UUID, orgID uuid.UUID) (*PendingTagValue, error) {
	row := q.db.QueryRowContext(ctx, getPendingTagValue, iD, orgID)
	var i PendingTagValue
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TagKeyID,
		&i.ExtractedValue,
		&i.Source,
		&i.SourceRuleID,
		&i.HitCount,
		&i.SuggestedValue,
		&i.Status,
		&i.FirstSeenAt,
	)
	return &i, err
}

const getTagKey = `-- name: GetTagKey :one
SELECT id, org_id, key, label, value_controlled, required_at_collection,
       allow_path_var, system_reserved, created_at
FROM tag_keys
WHERE org_id = $1 AND key = $2
LIMIT 1
`

func (q *Queries) GetTagKey(ctx context.Context, orgID uuid.UUID, key string) (*TagKey, error) {
	row := q.db.QueryRowContext(ctx, getTagKey, orgID, key)
	var i TagKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Label,
		&i.ValueControlled,
		&i.RequiredAtCollection,
		&i.AllowPathVar,
		&i.SystemReserved,
		&i.CreatedAt,
	)
	return &i, err
}

const listPendingTagValues = `-- name: ListPendingTagValues :many
SELECT p.id, p.tag_key_id, k.key, p.extracted_value, p.source, p.source_rule_id,
       p.hit_count, p.suggested_value, p.first_seen_at
FROM pending_tag_values p
JOIN tag_keys k ON k.id = p.tag_key_id AND k.org_id = p.org_id
WHERE p.org_id = $1 AND p.status = 'pending'
ORDER BY p.hit_count DESC, p.first_seen_at ASC
`

type ListPendingTagValuesRow struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	TagKeyID       uuid.UUID      `db:"tag_key_id" json:"tag_key_id"`
	Key            string         `db:"key" json:"key"`
	ExtractedValue string         `db:"extracted_value" json:"extracted_value"`
	Source         string         `db:"source" json:"source"`
	SourceRuleID   uuid.NullUUID  `db:"source_rule_id" json:"source_rule_id"`
	HitCount       int32          `db:"hit_count" json:"hit_count"`
	SuggestedValue sql.NullString `db:"suggested_value" json:"suggested_value"`
	FirstSeenAt    time.Time      `db:"first_seen_at" json:"first_seen_at"`
}

func (q *Queries) ListPendingTagValues(ctx context.Context, orgID uuid.UUID) ([]*ListPendingTagValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTagValues, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListPendingTagValuesRow{}
	for rows.Next() {
		var i ListPendingTagValuesRow
		if err := rows.Scan(
			&i.ID,
			&i.TagKeyID,
			&i.Key,
			&i.ExtractedValue,
			&i.Source,
			&i.SourceRuleID,
			&i.HitCount,
			&i.SuggestedValue,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagKeys = `-- name: ListTagKeys :many
SELECT id, org_id, key, label, value_controlled, required_at_collection,
       allow_path_var, system_reserved, created_at
FROM tag_keys
WHERE org_id = $1
ORDER BY key ASC
`

func (q *Queries) ListTagKeys(ctx context.Context, orgID uuid.UUID) ([]*TagKey, error) {
	rows, err := q.db.QueryContext(ctx, listTagKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TagKey{}
	for rows.Next() {
		var i TagKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Label,
			&i.ValueControlled,
			&i.RequiredAtCollection,
			&i.AllowPathVar,
			&i.SystemReserved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagValues = `-- name: ListTagValues :many
SELECT id, tag_key_id, value, created_at
FROM tag_values
WHERE tag_key_id = $1
ORDER BY value ASC
`

func (q *Queries) ListTagValues(ctx context.Context, tagKeyID uuid.UUID) ([]*TagValue, error) {
	rows, err := q.db.QueryContext(ctx, listTagValues, tagKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TagValue{}
	for rows.Next() {
		var i TagValue
		if err := rows.Scan(
			&i.ID,
			&i.TagKeyID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagKey = `-- name: UpdateTagKey :one
UPDATE tag_keys
SET label = $3,
    value_controlled = $4,
    required_at_collection = $5,
    allow_path_var = $6
WHERE org_id = $1 AND key = $2
RETURNING id, org_id, key, label, value_controlled, required_at_collection,
          allow_path_var, system_reserved, created_at
`

type UpdateTagKeyParams struct {
	OrgID                uuid.UUID `db:"org_id" json:"org_id"`
	Key                  string    `db:"key" json:"key"`
	Label                string    `db:"label" json:"label"`
	ValueControlled      bool      `db:"value_controlled" json:"value_controlled"`
	RequiredAtCollection bool      `db:"required_at_collection" json:"required_at_collection"`
	AllowPathVar         bool      `db:"allow_path_var" json:"allow_path_var"`
}

func (q *Queries) UpdateTagKey(ctx context.Context, arg UpdateTagKeyParams) (*TagKey, error) {
	row := q.db.QueryRowContext(ctx, updateTagKey,
		arg.OrgID,
		arg.Key,
		arg.Label,
		arg.ValueControlled,
		arg.RequiredAtCollection,
		arg.AllowPathVar,
	)
	var i TagKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Label,
		&i.ValueControlled,
		&i.RequiredAtCollection,
		&i.AllowPathVar,
		&i.SystemReserved,
		&i.CreatedAt,
	)
	return &i, err
}
