// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTagKey = `-- name: CreateTagKey :one
INSERT INTO tag_keys (org_id, key, label, value_controlled, required_at_collection, allow_path_var)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, key, label, value_controlled, required_at_collection,
          allow_path_var, system_reserved, created_at
`

type CreateTagKeyParams struct {
	OrgID                uuid.UUID `db:"org_id" json:"org_id"`
	Key                  string    `db:"key" json:"key"`
	Label                string    `db:"label" json:"label"`
	ValueControlled      bool      `db:"value_controlled" json:"value_controlled"`
	RequiredAtCollection bool      `db:"required_at_collection" json:"required_at_collection"`
	AllowPathVar         bool      `db:"allow_path_var" json:"allow_path_var"`
}

func (q *Queries) CreateTagKey(ctx context.Context, arg CreateTagKeyParams) (*TagKey, error) {
	row := q.db.QueryRowContext(ctx, createTagKey,
		arg.OrgID,
		arg.Key,
		arg.Label,
		arg.ValueControlled,
		arg.RequiredAtCollection,
		arg.AllowPathVar,
	)
	var i TagKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Label,
		&i.ValueControlled,
		&i.RequiredAtCollection,
		&i.AllowPathVar,
		&i.SystemReserved,
		&i.CreatedAt,
	)
	return &i, err
}

const createTagValue = `-- name: CreateTagValue :one
INSERT INTO tag_values (tag_key_id, value)
VALUES ($1, $2)
RETURNING id, tag_key_id, value, created_at
`

func (q *Queries) CreateTagValue(ctx context.Context, tagKeyID uuid.UUID, value string) (*TagValue, error) {
	row := q.db.QueryRowContext(ctx, createTagValue, tagKeyID, value)
	var i TagValue
	err := row.Scan(
		&i.ID,
		&i.TagKeyID,
		&i.Value,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteTagKey = `-- name: DeleteTagKey :execrows
DELETE FROM tag_keys WHERE org_id = $1 AND key = $2
`

func (q *Queries) DeleteTagKey(ctx context.Context, orgID uuid.UUID, key string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTagKey, orgID, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTagValue = `-- name: DeleteTagValue :execrows
DELETE FROM tag_values WHERE id = $1 AND tag_key_id = $2
`

func (q *Queries) DeleteTagValue(ctx context.Context, iD uuid.UUID, tagKeyID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTagValue, iD, tagKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTagKey = `-- name: GetTagKey :one
SELECT id, org_id, key, label, value_controlled, required_at_collection,
       allow_path_var, system_reserved, created_at
FROM tag_keys
WHERE org_id = $1 AND key = $2
LIMIT 1
`

func (q *Queries) GetTagKey(ctx context.Context, orgID uuid.UUID, key string) (*TagKey, error) {
	row := q.db.QueryRowContext(ctx, getTagKey, orgID, key)
	var i TagKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Label,
		&i.ValueControlled,
		&i.RequiredAtCollection,
		&i.AllowPathVar,
		&i.SystemReserved,
		&i.CreatedAt,
	)
	return &i, err
}

const listTagKeys = `-- name: ListTagKeys :many
SELECT id, org_id, key, label, value_controlled, required_at_collection,
       allow_path_var, system_reserved, created_at
FROM tag_keys
WHERE org_id = $1
ORDER BY key ASC
`

func (q *Queries) ListTagKeys(ctx context.Context, orgID uuid.UUID) ([]*TagKey, error) {
	rows, err := q.db.QueryContext(ctx, listTagKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TagKey{}
	for rows.Next() {
		var i TagKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Label,
			&i.ValueControlled,
			&i.RequiredAtCollection,
			&i.AllowPathVar,
			&i.SystemReserved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagValues = `-- name: ListTagValues :many
SELECT id, tag_key_id, value, created_at
FROM tag_values
WHERE tag_key_id = $1
ORDER BY value ASC
`

func (q *Queries) ListTagValues(ctx context.Context, tagKeyID uuid.UUID) ([]*TagValue, error) {
	rows, err := q.db.QueryContext(ctx, listTagValues, tagKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TagValue{}
	for rows.Next() {
		var i TagValue
		if err := rows.Scan(
			&i.ID,
			&i.TagKeyID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagKey = `-- name: UpdateTagKey :one
UPDATE tag_keys
SET label = $3,
    value_controlled = $4,
    required_at_collection = $5,
    allow_path_var = $6
WHERE org_id = $1 AND key = $2
RETURNING id, org_id, key, label, value_controlled, required_at_collection,
          allow_path_var, system_reserved, created_at
`

type UpdateTagKeyParams struct {
	OrgID                uuid.UUID `db:"org_id" json:"org_id"`
	Key                  string    `db:"key" json:"key"`
	Label                string    `db:"label" json:"label"`
	ValueControlled      bool      `db:"value_controlled" json:"value_controlled"`
	RequiredAtCollection bool      `db:"required_at_collection" json:"required_at_collection"`
	AllowPathVar         bool      `db:"allow_path_var" json:"allow_path_var"`
}

func (q *Queries) UpdateTagKey(ctx context.Context, arg UpdateTagKeyParams) (*TagKey, error) {
	row := q.db.QueryRowContext(ctx, updateTagKey,
		arg.OrgID,
		arg.Key,
		arg.Label,
		arg.ValueControlled,
		arg.RequiredAtCollection,
		arg.AllowPathVar,
	)
	var i TagKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Label,
		&i.ValueControlled,
		&i.RequiredAtCollection,
		&i.AllowPathVar,
		&i.SystemReserved,
		&i.CreatedAt,
	)
	return &i, err
}
