// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    org_id,
    username,
    email,
    password_hash,
    role
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, org_id, username, email, password_hash, role, is_active, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	OrgID        uuid.UUID      `db:"org_id" json:"org_id"`
	Username     string         `db:"username" json:"username"`
	Email        sql.NullString `db:"email" json:"email"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	Role         UserRole       `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.OrgID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, org_id, username, email, password_hash, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, org_id, username, email, password_hash, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE username = $1
  AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, org_id, username, email, password_hash, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context, orgID uuid.UUID) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users
SET is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserActive(ctx context.Context, iD uuid.UUID, isActive bool) error {
	_, err := q.db.ExecContext(ctx, updateUserActive, iD, isActive)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserPassword(ctx context.Context, iD uuid.UUID, passwordHash string) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, iD, passwordHash)
	return err
}
