"""Agent model — represents an edge agent record from the control plane."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class Agent:
    """An edge agent record as returned by the control plane API.

    Attributes:
        id: UUID of the agent.
        name: Human-readable display name.
        fingerprint: Device-unique identifier generated by the agent.
        status: Lifecycle status (``"pending"`` / ``"approved"`` / ``"running"``
            / ``"offline"`` / ``"revoked"``).
        ip_address: Last known IP address of the agent, or None.
        last_seen_at: ISO-8601 timestamp of the last heartbeat, or None.
        approved_at: ISO-8601 timestamp when the agent was approved, or None.
        created_at: ISO-8601 creation timestamp.
        updated_at: ISO-8601 last-updated timestamp.
    """

    id: str
    name: str
    fingerprint: str
    status: str
    ip_address: Optional[str]
    last_seen_at: Optional[str]
    approved_at: Optional[str]
    created_at: str
    updated_at: str

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Agent":
        """Construct an Agent from an API response dict.

        Args:
            data: Decoded JSON dict from the ``/api/v1/agents`` endpoint.

        Returns:
            A populated :class:`Agent` instance.
        """
        return cls(
            id=data["id"],
            name=data["name"],
            fingerprint=data.get("fingerprint", ""),
            status=data.get("status", ""),
            ip_address=data.get("ip_address"),
            last_seen_at=data.get("last_seen_at"),
            approved_at=data.get("approved_at"),
            created_at=data.get("created_at", ""),
            updated_at=data.get("updated_at", ""),
        )
